-- MySQL Script generated by MySQL Workbench
-- Fri Jun 25 14:02:31 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_CHECKS=@_CHECKS,_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `corpus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `corpus` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` TINYTEXT NOT NULL,
  `abbr` TINYTEXT NOT NULL,
  `description` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  FULLTEXT INDEX `nom` (`name`),
  FULLTEXT INDEX `abbr` (`abbr`),
  FULLTEXT INDEX `description` (`description`));


-- -----------------------------------------------------
-- Table `langues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `langues` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` TINYTEXT NOT NULL,
  `abbr` TINYTEXT NOT NULL,
  `description` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  FULLTEXT INDEX `nom` (`name`),
  FULLTEXT INDEX `abbr` (`abbr`),
  FULLTEXT INDEX `description` (`description`));


-- -----------------------------------------------------
-- Table `versions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `versions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` TINYTEXT NOT NULL,
  `abbr` TINYTEXT NOT NULL,
  `description` LONGTEXT NULL,
  `corpus_id` INT UNSIGNED NOT NULL,
  `langues_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  FULLTEXT INDEX `nom` (`name`),
  FULLTEXT INDEX `abbr` (`abbr`),
  FULLTEXT INDEX `description` (`description`),
  INDEX `fk_versions_corpus_idx` (`corpus_id` ASC),
  INDEX `fk_versions_langues1_idx` (`langues_id` ASC),
  CONSTRAINT `fk_versions_corpus`
    FOREIGN KEY (`corpus_id`)
    REFERENCES `corpus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_versions_langues1`
    FOREIGN KEY (`langues_id`)
    REFERENCES `langues` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `livres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livres` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` TINYTEXT NOT NULL,
  `abbr` TINYTEXT NOT NULL,
  `description` LONGTEXT NULL,
  `versions_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  FULLTEXT INDEX `nom` (`name`),
  FULLTEXT INDEX `abbr` (`abbr`),
  FULLTEXT INDEX `description` (`description`),
  INDEX `fk_livres_versions1_idx` (`versions_id` ASC),
  CONSTRAINT `fk_livres_versions1`
    FOREIGN KEY (`versions_id`)
    REFERENCES `versions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `textes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `textes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `chapitre` INT UNSIGNED NULL,
  `verset` INT UNSIGNED NULL,
  `texte` LONGTEXT NOT NULL,
  `livres_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `ordre` (`chapitre` ASC, `verset` ASC),
  FULLTEXT INDEX `texte` (`texte`),
  INDEX `fk_textes_livres1_idx` (`livres_id` ASC),
  CONSTRAINT `fk_textes_livres1`
    FOREIGN KEY (`livres_id`)
    REFERENCES `livres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

INSERT INTO `textes` (`chapitre`, `verset`, `texte`, `livres_id`) VALUES 
('1', '1', 'AU COMMENCEMENT, Dieu créa le ciel et la terre.', '1'), 
('1', '2', 'La terre était informe et vide, les ténèbres étaient au-dessus de l’abîme et le souffle de Dieu planait au-dessus des eaux.', '1'), 
('1', '3', 'Dieu dit : « Que la lumière soit. » Et la lumière fut.', '1'), 
('1', '4', 'Dieu vit que la lumière était bonne, et Dieu sépara la lumière des ténèbres.', '1'), 
('1', '5', 'Dieu appela la lumière « jour », il appela les ténèbres « nuit ». Il y eut un soir, il y eut un matin : premier jour.', '1'), 
('1', '6', 'Et Dieu dit : « Qu’il y ait un firmament au milieu des eaux, et qu’il sépare les eaux. »', '1'), 
('1', '7', 'Dieu fit le firmament, il sépara les eaux qui sont au-dessous du firmament et les eaux qui sont au-dessus. Et ce fut ainsi.', '1'), 
('1', '8', 'Dieu appela le firmament « ciel ». Il y eut un soir, il y eut un matin : deuxième jour.', '1'), 
('1', '9', 'Et Dieu dit : « Les eaux qui sont au-dessous du ciel, qu’elles se rassemblent en un seul lieu, et que paraisse la terre ferme. » Et ce fut ainsi.', '1'), 
('1', '10', 'Dieu appela la terre ferme « terre », et il appela la masse des eaux « mer ». Et Dieu vit que cela était bon.', '1'), 
('1', '11', 'Dieu dit : « Que la terre produise l’herbe, la plante qui porte sa semence, et que, sur la terre, l’arbre à fruit donne, selon son espèce, le fruit qui porte sa semence. » Et ce fut ainsi.', '1'), 
('1', '12', 'La terre produisit l’herbe, la plante qui porte sa semence, selon son espèce, et l’arbre qui donne, selon son espèce, le fruit qui porte sa semence. Et Dieu vit que cela était bon.', '1'), 
('1', '13', 'Il y eut un soir, il y eut un matin : troisième jour.', '1'), 
('1', '14', 'Et Dieu dit : « Qu’il y ait des luminaires au firmament du ciel, pour séparer le jour de la nuit ; qu’ils servent de signes pour marquer les fêtes, les jours et les années ;', '1'), 
('1', '15', 'et qu’ils soient, au firmament du ciel, des luminaires pour éclairer la terre. » Et ce fut ainsi.', '1'), 
('1', '16', 'Dieu fit les deux grands luminaires : le plus grand pour commander au jour, le plus petit pour commander à la nuit ; il fit aussi les étoiles.', '1'), 
('1', '17', 'Dieu les plaça au firmament du ciel pour éclairer la terre,', '1'), 
('1', '18', 'pour commander au jour et à la nuit, pour séparer la lumière des ténèbres. Et Dieu vit que cela était bon.', '1'), 
('1', '19', 'Il y eut un soir, il y eut un matin : quatrième jour.', '1'), 
('1', '20', 'Et Dieu dit : « Que les eaux foisonnent d’une profusion d’êtres vivants, et que les oiseaux volent au-dessus de la terre, sous le firmament du ciel. »', '1'), 
('1', '21', 'Dieu créa, selon leur espèce, les grands monstres marins, tous les êtres vivants qui vont et viennent et foisonnent dans les eaux, et aussi, selon leur espèce, tous les oiseaux qui volent. Et Dieu vit que cela était bon.', '1'), 
('1', '22', 'Dieu les bénit par ces paroles : « Soyez féconds et multipliez-vous, remplissez les mers, que les oiseaux se multiplient sur la terre. »', '1'), 
('1', '23', 'Il y eut un soir, il y eut un matin : cinquième jour.', '1'), 
('1', '24', 'Et Dieu dit : « Que la terre produise des êtres vivants selon leur espèce, bestiaux, bestioles et bêtes sauvages selon leur espèce. » Et ce fut ainsi.', '1'), 
('1', '25', 'Dieu fit les bêtes sauvages selon leur espèce, les bestiaux selon leur espèce, et toutes les bestioles de la terre selon leur espèce. Et Dieu vit que cela était bon.', '1'), 
('1', '26', 'Dieu dit : « Faisons l’homme à notre image, selon notre ressemblance. Qu’il soit le maître des poissons de la mer, des oiseaux du ciel, des bestiaux, de toutes les bêtes sauvages, et de toutes les bestioles qui vont et viennent sur la terre. »', '1'), 
('1', '27', 'Dieu créa l’homme à son image, à l’image de Dieu il le créa, il les créa homme et femme.', '1'), 
('1', '28', 'Dieu les bénit et leur dit : « Soyez féconds et multipliez-vous, remplissez la terre et soumettez-la. Soyez les maîtres des poissons de la mer, des oiseaux du ciel, et de tous les animaux qui vont et viennent sur la terre. »', '1'), 
('1', '29', 'Dieu dit encore : « Je vous donne toute plante qui porte sa semence sur toute la surface de la terre, et tout arbre dont le fruit porte sa semence : telle sera votre nourriture.', '1'), 
('1', '30', 'À tous les animaux de la terre, à tous les oiseaux du ciel, à tout ce qui va et vient sur la terre et qui a souffle de vie, je donne comme nourriture toute herbe verte. » Et ce fut ainsi.', '1'), 
('1', '31', 'Et Dieu vit tout ce qu’il avait fait ; et voici : cela était très bon. Il y eut un soir, il y eut un matin : sixième jour.', '1'), 
('2', '1', 'Ainsi furent achevés le ciel et la terre, et tout leur déploiement.', '1'), 
('2', '2', 'Le septième jour, Dieu avait achevé l’œuvre qu’il avait faite. Il se reposa, le septième jour, de toute l’œuvre qu’il avait faite.', '1'), 
('2', '3', 'Et Dieu bénit le septième jour : il le sanctifia puisque, ce jour-là, il se reposa de toute l’œuvre de création qu’il avait faite.', '1'), 
('2', '4', 'Telle fut l’origine du ciel et de la terre lorsqu’ils furent créés. Lorsque le Seigneur Dieu fit la terre et le ciel,', '1'), 
('2', '5', 'aucun buisson n’était encore sur la terre, aucune herbe n’avait poussé, parce que le Seigneur Dieu n’avait pas encore fait pleuvoir sur la terre, et il n’y avait pas d’homme pour travailler le sol.', '1'), 
('2', '6', 'Mais une source montait de la terre et irriguait toute la surface du sol.', '1'), 
('2', '7', 'Alors le Seigneur Dieu modela l’homme avec la poussière tirée du sol ; il insuffla dans ses narines le souffle de vie, et l’homme devint un être vivant.', '1'), 
('2', '8', 'Le Seigneur Dieu planta un jardin en Éden, à l’orient, et y plaça l’homme qu’il avait modelé.', '1'), 
('2', '9', 'Le Seigneur Dieu fit pousser du sol toutes sortes d’arbres à l’aspect désirable et aux fruits savoureux ; il y avait aussi l’arbre de vie au milieu du jardin, et l’arbre de la connaissance du bien et du mal.', '1'), 
('2', '10', 'Un fleuve sortait d’Éden pour irriguer le jardin ; puis il se divisait en quatre bras :', '1'), 
('2', '11', 'le premier s’appelle le Pishone, il contourne tout le pays de Havila où l’on trouve de l’or', '1'), 
('2', '12', '– et l’or de ce pays est bon – ainsi que de l’ambre jaune et de la cornaline ;', '1'), 
('2', '13', 'le deuxième fleuve s’appelle le Guihone, il contourne tout le pays de Koush ;', '1'), 
('2', '14', 'le troisième fleuve s’appelle le Tigre, il coule à l’est d’Assour ; le quatrième fleuve est l’Euphrate.', '1'), 
('2', '15', 'Le Seigneur Dieu prit l’homme et le conduisit dans le jardin d’Éden pour qu’il le travaille et le garde.', '1'), 
('2', '16', 'Le Seigneur Dieu donna à l’homme cet ordre : « Tu peux manger les fruits de tous les arbres du jardin ;', '1'), 
('2', '17', 'mais l’arbre de la connaissance du bien et du mal, tu n’en mangeras pas ; car, le jour où tu en mangeras, tu mourras. »', '1'), 
('2', '18', 'Le Seigneur Dieu dit : « Il n’est pas bon que l’homme soit seul. Je vais lui faire une aide qui lui correspondra. »', '1'), 
('2', '19', 'Avec de la terre, le Seigneur Dieu modela toutes les bêtes des champs et tous les oiseaux du ciel, et il les amena vers l’homme pour voir quels noms il leur donnerait. C’étaient des êtres vivants, et l’homme donna un nom à chacun.', '1'), 
('2', '20', 'L’homme donna donc leurs noms à tous les animaux, aux oiseaux du ciel et à toutes les bêtes des champs. Mais il ne trouva aucune aide qui lui corresponde.', '1'), 
('2', '21', 'Alors le Seigneur Dieu fit tomber sur lui un sommeil mystérieux, et l’homme s’endormit. Le Seigneur Dieu prit une de ses côtes, puis il referma la chair à sa place.', '1'), 
('2', '22', 'Avec la côte qu’il avait prise à l’homme, il façonna une femme et il l’amena vers l’homme.', '1'), 
('2', '23', 'L’homme dit alors : « Cette fois-ci, voilà l’os de mes os et la chair de ma chair ! On l’appellera femme – Ishsha –, elle qui fut tirée de l’homme – Ish. »', '1'), 
('2', '24', 'À cause de cela, l’homme quittera son père et sa mère, il s’attachera à sa femme, et tous deux ne feront plus qu’un.', '1'), 
('2', '25', 'Tous les deux, l’homme et sa femme, étaient nus, et ils n’en éprouvaient aucune honte l’un devant l’autre.', '1'); 

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET_CHECKS=@OLD_CHECKS;
