name: Publier Master sur Cpanel / prod
on:
  push:
    branches:
      - master
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.FTP_SERVER_PROD }}
        ftp-username: ${{ secrets.FTP_USERNAME_PROD }}
        ftp-password: ${{ secrets.FTP_PASSWORD_PROD }}
